export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as Services } from './Services'
export { default as Features } from './Features'
export { default as Footer } from './Footer'